// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orders/temp.proto

package orders

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("orders/temp.proto", fileDescriptor_09e5765820be8085) }

var fileDescriptor_09e5765820be8085 = []byte{
	// 67 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x2f, 0x4a, 0x49,
	0x2d, 0x2a, 0xd6, 0x2f, 0x49, 0xcd, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x37, 0x12, 0xe4,
	0xe2, 0xf7, 0xc9, 0xcc, 0x4b, 0xf5, 0x2c, 0x49, 0xcd, 0x0d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e,
	0x4d, 0x62, 0x03, 0xcb, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x71, 0x52, 0x88, 0x2e,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LineItemServiceClient is the client API for LineItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LineItemServiceClient interface {
}

type lineItemServiceClient struct {
	cc *grpc.ClientConn
}

func NewLineItemServiceClient(cc *grpc.ClientConn) LineItemServiceClient {
	return &lineItemServiceClient{cc}
}

// LineItemServiceServer is the server API for LineItemService service.
type LineItemServiceServer interface {
}

// UnimplementedLineItemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLineItemServiceServer struct {
}

func RegisterLineItemServiceServer(s *grpc.Server, srv LineItemServiceServer) {
	s.RegisterService(&_LineItemService_serviceDesc, srv)
}

var _LineItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LineItemService",
	HandlerType: (*LineItemServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "orders/temp.proto",
}
