// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/customers.proto

package orders

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CustomerId struct {
	DomainId             int64    `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerId) Reset()         { *m = CustomerId{} }
func (m *CustomerId) String() string { return proto.CompactTextString(m) }
func (*CustomerId) ProtoMessage()    {}
func (*CustomerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2bec1e7b4de0822, []int{0}
}

func (m *CustomerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerId.Unmarshal(m, b)
}
func (m *CustomerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerId.Marshal(b, m, deterministic)
}
func (m *CustomerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerId.Merge(m, src)
}
func (m *CustomerId) XXX_Size() int {
	return xxx_messageInfo_CustomerId.Size(m)
}
func (m *CustomerId) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerId.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerId proto.InternalMessageInfo

func (m *CustomerId) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *CustomerId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Customer struct {
	DomainId             int64                `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Id                   int64                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Email                string               `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string               `protobuf:"bytes,11,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,12,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	State                string               `protobuf:"bytes,13,opt,name=state,proto3" json:"state,omitempty"`
	Note                 string               `protobuf:"bytes,14,opt,name=note,proto3" json:"note,omitempty"`
	Phone                string               `protobuf:"bytes,15,opt,name=phone,proto3" json:"phone,omitempty"`
	DefaultAddress       *Address             `protobuf:"bytes,16,opt,name=default_address,json=defaultAddress,proto3" json:"default_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2bec1e7b4de0822, []int{1}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *Customer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Customer) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Customer) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Customer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Customer) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Customer) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Customer) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Customer) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Customer) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Customer) GetDefaultAddress() *Address {
	if m != nil {
		return m.DefaultAddress
	}
	return nil
}

func init() {
	proto.RegisterType((*CustomerId)(nil), "CustomerId")
	proto.RegisterType((*Customer)(nil), "Customer")
}

func init() { proto.RegisterFile("proto/customers.proto", fileDescriptor_b2bec1e7b4de0822) }

var fileDescriptor_b2bec1e7b4de0822 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcf, 0xee, 0xd2, 0x40,
	0x10, 0x4e, 0x8b, 0x34, 0xed, 0xa0, 0x60, 0x36, 0x68, 0x36, 0x25, 0x28, 0xe1, 0xc4, 0xc5, 0x12,
	0xf1, 0xc4, 0x11, 0xd1, 0x18, 0x2e, 0x1e, 0x1a, 0xbd, 0x78, 0x69, 0x16, 0x76, 0xc0, 0x26, 0xdd,
	0x6e, 0xb3, 0x3b, 0x3d, 0xf8, 0x68, 0xbe, 0x96, 0x4f, 0x60, 0xba, 0xdd, 0x86, 0xa8, 0x51, 0xf3,
	0xbb, 0xed, 0xf7, 0x6f, 0x9a, 0x6f, 0x3a, 0xf0, 0xac, 0x31, 0x9a, 0xf4, 0xf6, 0xd2, 0x5a, 0xd2,
	0x0a, 0x8d, 0xcd, 0x1c, 0x4e, 0x17, 0x37, 0xad, 0x6f, 0x15, 0x6e, 0x1d, 0x3a, 0xb7, 0xd7, 0x2d,
	0xaa, 0x86, 0xbe, 0x79, 0xf1, 0xe5, 0xef, 0x22, 0x95, 0x0a, 0x2d, 0x09, 0xd5, 0x78, 0x83, 0x1f,
	0x2a, 0xa4, 0x34, 0x68, 0x2d, 0xfa, 0xa1, 0xeb, 0x3d, 0xc0, 0xd1, 0x7f, 0xe7, 0x24, 0xd9, 0x02,
	0x12, 0xa9, 0x95, 0x28, 0xeb, 0xa2, 0x94, 0x3c, 0x58, 0x05, 0x9b, 0x51, 0x1e, 0xf7, 0xc4, 0x49,
	0xb2, 0x29, 0x84, 0xa5, 0xe4, 0xa1, 0x63, 0xc3, 0x52, 0xae, 0x7f, 0x84, 0x10, 0x0f, 0xd9, 0x07,
	0x25, 0xd9, 0x1e, 0xe0, 0x62, 0x50, 0x10, 0xca, 0x42, 0x10, 0x8f, 0x57, 0xc1, 0x66, 0xb2, 0x4b,
	0xb3, 0xbe, 0x41, 0x36, 0x34, 0xc8, 0x3e, 0x0d, 0x0d, 0xf2, 0xc4, 0xbb, 0x0f, 0xd4, 0x45, 0xdb,
	0x46, 0x0e, 0xd1, 0xe4, 0xff, 0x51, 0xef, 0x3e, 0x10, 0x9b, 0xc3, 0x18, 0x95, 0x28, 0x2b, 0x0e,
	0xab, 0x60, 0x93, 0xe4, 0x3d, 0x60, 0x4b, 0x80, 0x6b, 0x69, 0x2c, 0x15, 0xb5, 0x50, 0xc8, 0x27,
	0x4e, 0x4a, 0x1c, 0xf3, 0x51, 0x28, 0xec, 0x7a, 0x55, 0x62, 0x50, 0x1f, 0x3b, 0x35, 0xee, 0x08,
	0x27, 0xce, 0x61, 0x6c, 0x49, 0x10, 0xf2, 0x27, 0xfd, 0x44, 0x07, 0x18, 0x83, 0x47, 0xb5, 0x26,
	0xe4, 0x53, 0x47, 0xba, 0x77, 0xe7, 0x6c, 0xbe, 0xea, 0x1a, 0xf9, 0xac, 0x77, 0x3a, 0xc0, 0x5e,
	0xc3, 0x4c, 0xe2, 0x55, 0xb4, 0x15, 0x15, 0xfe, 0xbf, 0xf0, 0xa7, 0xae, 0x51, 0x9c, 0x1d, 0x7a,
	0x9c, 0x4f, 0xbd, 0xc1, 0xe3, 0xdd, 0xf7, 0x00, 0x92, 0x61, 0xe9, 0x96, 0xbd, 0x80, 0xe8, 0xe8,
	0x56, 0xc3, 0x92, 0x6c, 0x60, 0xd3, 0xfb, 0xb3, 0xd3, 0x3f, 0xbb, 0xfe, 0xff, 0xd2, 0x2d, 0x1a,
	0xfa, 0x8b, 0xfe, 0x0a, 0xa2, 0x77, 0x58, 0x21, 0x21, 0x9b, 0x64, 0xf7, 0x33, 0x49, 0x9f, 0xff,
	0xb1, 0xf0, 0xf7, 0xdd, 0x29, 0xb2, 0x25, 0x8c, 0x3e, 0x20, 0xfd, 0xea, 0xbd, 0x4f, 0x7b, 0x1b,
	0x7f, 0x89, 0xb4, 0x91, 0x68, 0xec, 0x39, 0x72, 0xc1, 0x37, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x99, 0xcb, 0x3e, 0x60, 0xea, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomersClient is the client API for Customers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomersClient interface {
	Create(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*Customer, error)
	Update(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*Customer, error)
	Upsert(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*Customer, error)
	Delete(ctx context.Context, in *CustomerId, opts ...grpc.CallOption) (*empty.Empty, error)
	Get(ctx context.Context, in *CustomerId, opts ...grpc.CallOption) (*Customer, error)
}

type customersClient struct {
	cc *grpc.ClientConn
}

func NewCustomersClient(cc *grpc.ClientConn) CustomersClient {
	return &customersClient{cc}
}

func (c *customersClient) Create(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, "/Customers/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) Update(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, "/Customers/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) Upsert(ctx context.Context, in *Customer, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, "/Customers/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) Delete(ctx context.Context, in *CustomerId, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Customers/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customersClient) Get(ctx context.Context, in *CustomerId, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, "/Customers/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomersServer is the server API for Customers service.
type CustomersServer interface {
	Create(context.Context, *Customer) (*Customer, error)
	Update(context.Context, *Customer) (*Customer, error)
	Upsert(context.Context, *Customer) (*Customer, error)
	Delete(context.Context, *CustomerId) (*empty.Empty, error)
	Get(context.Context, *CustomerId) (*Customer, error)
}

// UnimplementedCustomersServer can be embedded to have forward compatible implementations.
type UnimplementedCustomersServer struct {
}

func (*UnimplementedCustomersServer) Create(ctx context.Context, req *Customer) (*Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedCustomersServer) Update(ctx context.Context, req *Customer) (*Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedCustomersServer) Upsert(ctx context.Context, req *Customer) (*Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (*UnimplementedCustomersServer) Delete(ctx context.Context, req *CustomerId) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedCustomersServer) Get(ctx context.Context, req *CustomerId) (*Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterCustomersServer(s *grpc.Server, srv CustomersServer) {
	s.RegisterService(&_Customers_serviceDesc, srv)
}

func _Customers_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Customer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Customers/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).Create(ctx, req.(*Customer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Customer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Customers/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).Update(ctx, req.(*Customer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Customer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Customers/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).Upsert(ctx, req.(*Customer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Customers/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).Delete(ctx, req.(*CustomerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customers_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomersServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Customers/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomersServer).Get(ctx, req.(*CustomerId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Customers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Customers",
	HandlerType: (*CustomersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Customers_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Customers_Update_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _Customers_Upsert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Customers_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Customers_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/customers.proto",
}
